### ISSUE TITLE
May I get some sql files?

### ISSUE THREAD

**Issue by WithSunny** [liuqingli/CCLearner#2]
Hello, my name is Dong. I knew this project from the paper: CCLearner: A Deep Learning-Based Clone Detection Approach. I am interested in your approach. When I downloaded the project, I found that the project is short of some necessary documents: era_bigclonebench.sql.tar.gz and era_bcb_sample.tar.gz. May I get these? I would be grateful if you could give me these files. Thank you very much.

**Comment by liuqingli** [comment]
Hi, thanks for your interest in CCLEARNER! Since the clone detection benchmark bigclonebench is proposed and maintained by Dr. Roy's team, please refer to [their repo](https://github.com/clonebench/BigCloneBench) for more details. The two files your mentioned is in ERA (Updated). Hoping this helps.

**Comment by WithSunny** [comment]
Thanks for your reply and assistance！
